---
    version: "2.1"
    services:
      rdesktop:
        image: lscr.io/linuxserver/rdesktop:fedora-i3
        container_name: fedora-i3
        security_opt:
          - seccomp:unconfined #optional
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Amsterdam
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock #optional
          - /home/pi/docker/fedora-i3/config:/config #optional
        ports:
          - 15:3389
        devices:
          - /dev/dri:/dev/dri #optional
        shm_size: "1gb" #optional
        restart: unless-stopped